### ISSUE TITLE
working directory cancel error

### ISSUE THREAD

**Issue by xiaoguang1988** [metaOmic/metaOmics#10]
When I set working directory, if I click cancel, the software will go die.

**Comment by CHPGenetics** [comment]
1. Resolved

**Comment by CHPGenetics** [comment]
13        try({
  14            validate()
  15            DB <- reactiveValues(acitve=study,transpose=lapply(study@datasets,t))
= 16            print(is.null(study)) #FALSE??
= 17            print(is.null(DB$active)) #TRUE??
= 18

**Comment by schwannden** [comment]
what's this?

**Comment by CHPGenetics** [comment]
It looks the study is not null but DB$active is

**Comment by schwannden** [comment]
DB <- reactiveValues(acitve=study,transpose=lapply(study@datasets,t))
looks strange? you have study=study, but where is the study on the right hand side?

**Comment by schwannden** [comment]
@CHPGenetics  let's stop discussing this issue here, this issue is irrelevant to our discussion. Open a new issue if you want to discuss it.
