### ISSUE TITLE
Auto install packages

### ISSUE THREAD

**Issue by schwannden** [metaOmic/metaOmics#12]
We can check if individual packages are installed. If not, allow user to install the package they need instead of installing everything.

**Comment by schwannden** [comment]
There is a trade of here.
Providing auto install feature will take some time but is definitely feasible. But if we can wait until everyone put their packages on BioConductor or CRAN, we only need to make these packages the dependencies and these packages will be automatically installed.

So for now let's sit on this problem

**Comment by xiaoguang1988** [comment]
My comment is, e.g. if a user only want to use MetaDE, then he won't bother install metaClust at all.
So I think it would be nice if allow user to install packages whenever they need to, not install everything at once. What do you think?

**Comment by schwannden** [comment]
Yes it would be nice. If I have free time I will work on this

**Comment by schwannden** [comment]
@xiaoguang1988 @CHPGenetics This enhancement has been added to release 0.1.0, please help check if it works as expected.

**Comment by CHPGenetics** [comment]
This is an awesome function!

**Comment by schwannden** [comment]
@CHPGenetics @xiaoguang1988 The bug of install_github appears to be permission issue. If you start shiny in sudo permission (start R console in sudo, then start shiny), the issue should be resolved. @CHPGenetics Can you try it? If it really can be resolved this way, I'll just update the error message and README instruction

**Comment by CHPGenetics** [comment]
Restarted my machine and tested auto installing MetaDE. Installed successful. No more bug
