### ISSUE TITLE
After playing with metaOmics, I could not restart the software

### ISSUE THREAD

**Issue by xiaoguang1988** [metaOmic/metaOmics#19]
![screen shot 2016-08-29 at 3 34 18 pm](https://cloud.githubusercontent.com/assets/6474826/18064623/3308fbce-6dfe-11e6-821d-1f9697b414fd.png)

Another bug is that somehow my default working directory becomes date of today.
I am trying to figure out this happen, but I could not restart the software.

However, after waiting 1 min, I can restart the software.
The default working directory is:
![screen shot 2016-08-29 at 3 37 32 pm](https://cloud.githubusercontent.com/assets/6474826/18064703/91c464a0-6dfe-11e6-8330-57756d836591.png)

**Comment by schwannden** [comment]
Because the port is in use, it's network problem
