### ISSUE TITLE
enhancement of MetaClust

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/metaOmics#23]
This is not urgent. @CHPGenetics 

1, about: this metaClust panel serves as an UI for MetaSparseKmeans.
Starting with multiple studies, we could run MetaSparseKmeans with pre-specified number of clusters (K) and gene selection tuning parameter (Wbounds).
If you are not sure about what are good K and Wbounds, please try Tune K and Tune Wbounds panel.
Details are in the tutorials (https://github.com/metaOmic/tutorial/blob/master/metaOmics_turtorial.pdf). 

2: ? on Run Meta Sparse Kmeans: By clicking the button, you will get gene list selected by MetaSparseKmeans, heatmaps and class labels. All these results are saved in the default folder.

4, can we rescale the heatmap and other figures as what Anche did for MetaDE?

**Comment by schwannden** [comment]
@xiaoguang1988  Can you put number 3 in a separate issue? I want to discuss it with @CHPGenetics . But there are three issues here the discussion could be cluttered

**Comment by xiaoguang1988** [comment]
Issue 1 and 2 are resolved.
