### ISSUE TITLE
Default usage of MetaPath

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/metaOmics#26]
If use default setting to run MetaPath.
There is an error message:
![screen shot 2016-08-31 at 2 44 49 pm](https://cloud.githubusercontent.com/assets/6474826/18142320/0a188160-6f8b-11e6-8108-4e7dcd58481a.png)

**Comment by schwannden** [comment]
@xiaoguang1988  I can not reproduce this error after a number of testings, can you show me the steps to reproduce it?

**Comment by Caleb-Huo** [comment]
Alright, I will close this issue.
I will rerun it on weekend and report this if it happens again.
