### ISSUE TITLE
devtools installing error

### ISSUE THREAD

**Issue by CHPGenetics** [metaOmic/metaOmics#33]
> devtools::install_github("metaOmic/metaDE")
Downloading GitHub repo metaOmic/metaDE@master
from URL https://api.github.com/repos/metaOmic/metaDE/zipball/master
Error in eapply(ns_env(pkg), force, all.names = TRUE) : 
  cannot open file '/Users/ark/Library/R/3.3/library/MetaDE/R/MetaDE.rdb': No such file or directory
In addition: Warning message:
In eapply(ns_env(pkg), force, all.names = TRUE) :
  restarting interrupted promise evaluation

**But tools outside metaOmic could be installed
for instance**
> devtools::install_github("AnalytixWare/ShinySky")
**this works**

**Comment by CHPGenetics** [comment]
It worked for now. I'm committing this change so far for MetaPCA and will reissue it later if i encounter it later.

**Comment by xiaoguang1988** [comment]
cannot open file '/Users/ark/Library/R/3.3/library/MetaDE/R/MetaDE.rdb': No such file or directory
This error message, in my experience, means you don't have admin right.

**Comment by CHPGenetics** [comment]
Thank you .It sounds like so.
But I cannot test that. And it magically worked now.
But in future you may test it using: sudo R -e  "devtools::......." command
in terminal to see.
