### ISSUE TITLE
Failure in starting the application

### ISSUE THREAD

**Issue by matianzhou** [metaOmic/metaOmics#36]
Anyone experiencing the following issue? I am encountering this issue now but never experienced this before, I checked online and people said this is an issue with the port:

Listening on http://127.0.0.1:9987
Error in startServer(host, port, handlerManager$createHttpuvApp()) : 
  Failed to create server

**Comment by Caleb-Huo** [comment]
It seems the error is you already started a webpage using port 9987

**Comment by matianzhou** [comment]
Thanks, resolved.
