### ISSUE TITLE
metaDCN

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/metaOmics#40]
Cannot see metaDCN package name, it is not available on toolset either.
![screen shot 2016-10-11 at 9 25 23 am](https://cloud.githubusercontent.com/assets/6474826/19271955/c25c14d4-8f94-11e6-94f1-13727980b216.png)

**Comment by CHPGenetics** [comment]
Which branch are you on?

**Comment by Caleb-Huo** [comment]
Yes, I was on the wrong branch.
Thanks
