### ISSUE TITLE
enhancement of MetaDCN

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/metaOmics#41]
I got "no basic modules" at FDR 0.3.
I think it would be better to scroll the FDR bar and re-render the results, instead of running everything again. What do you think?
![screen shot 2016-10-13 at 5 10 02 pm](https://cloud.githubusercontent.com/assets/6474826/19367155/fee12532-9167-11e6-92fe-a51114d97d99.png)

**Comment by Caleb-Huo** [comment]
I also think some of the intermediate results can be saved. If the user revisit metaDCN, all the results can be reloaded. What do you think? Otherwise the saved rdata are kind of useless for biologists.
This comment is minor.

**Comment by lizhu06** [comment]
Should work now. Suggest first try 0.8 for both mean and variance filtering. It'll take several minutes for each step.

**Comment by Caleb-Huo** [comment]
1, If I click generate network, the error message is: object GeneNet not found.
2, A minor suggestion: case name and control name could be consistent with the clinical input (e.g. inv16)


![screen shot 2016-11-06 at 11 34 07 am](https://cloud.githubusercontent.com/assets/6474826/20039620/fb47682c-a414-11e6-9e24-f0fd42be54d5.png)

**Comment by lizhu06** [comment]
Did you re-install MetaDCN package?

**Comment by Caleb-Huo** [comment]
Oops, No, I didn't.

**Comment by Caleb-Huo** [comment]
It works well. How to present the final result, you may ask George.
2 minor issue:
1), case name and control could be actual clinical label instead of 1,2,3.
2), if I choose number of CPUs greater than 1, I will get the following error message.
![screen shot 2016-11-06 at 2 12 09 pm](https://cloud.githubusercontent.com/assets/6474826/20040764/44416fda-a42b-11e6-8b1b-c2226ba2133e.png)

**Comment by lizhu06** [comment]
1) The clinical labels work for me. I don't know why. Maybe re-install some packages?
2) I use snowfall package for parallel. I guess if the computer doesn't have multiple cores it generates such errors. I'll add a function to check if parallel is allowed. Thanks!

![image](https://cloud.githubusercontent.com/assets/20243615/20042703/c9ff6d90-a44c-11e6-985f-ad4b3cd55c77.png)
