### ISSUE TITLE
metaPCA save results

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/metaOmics#42]
After I run metaPCA, the plots are not automatically.
Is it possible to make it to be saved automatically? Or I can manually save it.

**Comment by Caleb-Huo** [comment]
Also makes the plot aligned horizontally. Make a scroll bar to roll left and right.

**Comment by CHPGenetics** [comment]
Solved, please check new version on feature/metaPCA branch. And I'll come back to close the issue
