### ISSUE TITLE
Preprocessing

### ISSUE THREAD

**Issue by lizhu06** [metaOmic/metaOmics#43]
Using the Leukemia dataset, shiny app preprocessing gives slightly different results from directly applying preproc package. For example, setting mean and variance cutoff to be 0.8. Shiny app gives 205 genes; preproc gives 206 genes. Similar problem is encountered when using 0.3 cutoff for both.

**Comment by Caleb-Huo** [comment]
In my case, Shiny gives 206 genes.
Not sure why but I suggest to uninstall preproc and re-install in again for RShiny
![screen shot 2016-11-06 at 11 32 05 am](https://cloud.githubusercontent.com/assets/6474826/20039601/afe1173e-a414-11e6-9466-af0567677efc.png)

**Comment by lizhu06** [comment]
Just uninstall and re-install preproc, still get the same problem. Weird!

![image](https://cloud.githubusercontent.com/assets/20243615/20042774/c82e319e-a44d-11e6-97e0-a8c5f0e280ca.png)

**Comment by lizhu06** [comment]
Found a typo in preproc/R/filter.R. 

In line 77. function(z)rank(apply(z[gene.mv,], 1, mean, na.rm=T))). Should the mean be replaced by sd?

**Comment by Caleb-Huo** [comment]
How about you fix this problem in your own branch?
I don't want to touch the master branch since all other features are relying on current master.
I will fix the issue when we need to merge everything together.
What do you think? @schwannden

**Comment by Caleb-Huo** [comment]
solved
