### ISSUE TITLE
pathway analysis

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/metaOmics#46]
In metaDE module, 
Couldn't find function PathAnalysis.
Another suggestion: can we make Fisher's exact test as default since it is more often used?

Parameters: 
log transformed: FALSE
filtering: 0.6, 0.6
Method: Fisher's method using Default number of DE genes
Others: default

![screen shot 2017-01-03 at 10 28 10 am](https://cloud.githubusercontent.com/assets/6474826/21612489/68663b92-d19f-11e6-8f29-27efdd67107d.png)

**Comment by matianzhou** [comment]
Did you use the most recent version of MetaDE? Can you remove and install MetaDE from MetaOmics homepage again, I tried out and the error never showed up.

As discussed before, we suggest using KS test as the default pathway analysis method for both MetaDE and MetaPath.

**Comment by Caleb-Huo** [comment]
1, I removed MetaDE. Then I cannot open MetaOmics homepage again.
It seems MetaDE is a pre-request for opening homepage of MetaOmics?
![screen shot 2017-01-03 at 11 06 58 am](https://cloud.githubusercontent.com/assets/6474826/21613840/f9626eea-d1a4-11e6-8df5-9d602a0043ff.png)

2, I see, thanks!

**Comment by matianzhou** [comment]
That's weird, I did the same thing (remove the package and restart MetaOmics) and it works. Can you remove, quit and then restart MetaOmics? Otherwise, let's resolve it tomorrow when we meet at school.

**Comment by Caleb-Huo** [comment]
Yes, that's what I did. 
I removed, quit and then restarted MetaOmics? I even re-pulled the software from GitHub.
Let's resolve it tomorrow.
