### ISSUE TITLE
some comments on metaClust

### ISSUE THREAD

**Issue by xiaoguang1988** [metaOmic/metaOmics#8]

**Comment by xiaoguang1988** [comment]
1, if there is no pre-loaded data, the data summary won't appear.

**Comment by CHPGenetics** [comment]
3. Multiple selection added with study name, in commit "Selectize added"
6. I assume you didn't set directory. So that'll make it be set to root directory. Do you want the error msg to be popped up at the setting-working-directory tab or each tool's tab?

**Comment by schwannden** [comment]
Ark, in the function "validate" we wrote today, you can add a check for working directory. That'll do it. So add
```R
if (DB.load.working.dir(db) == "") stop(MSG.no.working.dir)
```
in the validate function

**Comment by CHPGenetics** [comment]
All issues should be resolved by now. But I'm not closing this issue until confirmed by Caleb

**Comment by xiaoguang1988** [comment]
Several issues.
1, Anzhe will set default working directory using R.
2, default Maximum of K: 5. (For tuning number of clusters).
3, Select studies to be tuned, use original study names. (For tuning number of clusters).
4, solved. But set default to be 2, 16, 2. 1 is illegal for MetaSparseKmeans
5, For now let's leave it as it is.
6, solved.

**Comment by schwannden** [comment]
@CHPGenetics  @xiaoguang1988 lets try to open one issue for one problem in the future for better communication :)

**Comment by xiaoguang1988** [comment]
Yes, I will do that.

**Comment by xiaoguang1988** [comment]
@CHPGenetics 
It looks pretty good. Majority of the above issues are solved.
I have trouble viewing metaClust at this moment.
It seems to me "Select studies to be tuned" is still not fixed.
Can you make a "Drop-down menu" for "Select studies to be tuned" blank?

**Comment by xiaoguang1988** [comment]
It has been fixed.
Sorry for my mistake.
