### ISSUE TITLE
Some warning message, can we do dir check?

### ISSUE THREAD

**Issue by xiaoguang1988** [metaOmic/metaOmics#9]
> shiny::runApp('.', port=9877, launch.browser=T)
Loading required package: shiny
Warning: replacing previous import ‘limma::plotMA’ by ‘DESeq2::plotMA’ when loading ‘MetaDE’
Warning in dir.create(.Object@dir, recursive = T) :
  'data/studies' already exists
Warning in dir.create(paste(".Database", name, "meta", sep = "/"), recursive = T) :
  '.Database/studies/meta' already exists
Warning in dir.create(paste(".Database", name, "working", sep = "/"), recursive = T) :
  '.Database/studies/working' already exists
Warning in dir.create(.Object@activate.dir, recursive = T) :
  '.Database/studies/active' already exists

**Comment by xiaoguang1988** [comment]
Anzhe will improve default working directory to solve these problems.

**Comment by CHPGenetics** [comment]
That's good. But meanwhile checking if wd is null is still helpful

**Comment by schwannden** [comment]
@xiaoguang1988 this is not urgent, I will leave it for now

**Comment by xiaoguang1988** [comment]
Sounds good.

**Comment by schwannden** [comment]
@xiaoguang1988 I decided to enable all the warning messages. They are very important for debugging after all. I spent the whole morning and an hour in the afternoon debug for something I could have been found in warning message.

**Comment by xiaoguang1988** [comment]
This is not urgent.
My suggestion is not to suppress warning message.
My suggestion is we may do dir check before creating dir. If dir exist, we won't bother create a new one. 
Anyone, this is a minor issue.

**Comment by schwannden** [comment]
But this is exactly the same behaviour as the default behaviour. The warning message is just so you know there is a directory, it won't create a new one anyway if the directory exists?

**Comment by xiaoguang1988** [comment]
Alright, I see.
